version: '2'
services:
    php:
        build: php-fpm
        ports:
            - '9002:9000'
        volumes:
            - ../:/var/www/symfony:cached
            - ./logs/symfony:/var/www/symfony/var/logs:cached
        links:
            - mongo
    nginx:
        build: nginx
        ports:
            - '8080:80'
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx:cached
    mongo:
        image: mongo
        ports:
            - '27017:27017'
        volumes:
            - ./data/mongo:/data/db
